services: 
  -type: web
  name: Onrender.com
  runtime: node
  region: Frankfurt
  repo: git@github.com:LibelleQ/Render
  branch: main
  buildCommand: npm install
  startCommand: npm start
  autoDeploy: true
  plan: free
  envVars:
    - key: DATABASE_URL
      fromDatabase: 
        name: esgi2i2
        property: connectionString
databases:
  name: esgi2i2
  region: Frankfurt
  plan: free

```